### ISSUE TITLE
Role groups 

### ISSUE THREAD

**Issue by weedkiller** [akasarto/aspnet-mvc5-starter-template#3]
Hi it would be nice to also add suport for [RoleGroups](https://www.codeproject.com/Articles/808903/ASP-NET-Identity-Implementing-Group-Based-Permissi).
If Nike and Puma were separate groups/companies, we need to separate the managers/roles

`ManagersNIke`  for e.g. all roles (ManagNIke, BossNike, AdminNike)
`ManagersPuma`

**Comment by akasarto** [comment]
I'll have to keep the current implementation. I gave it a lot of thought but, in the end, the primary intention for this project is to be as simple as possible, so it can be easily modified to attend any derived work requirements.
