### ISSUE TITLE
Nuget Updates Bootstrap 4.1   & rebuild with latest .net 4.7.2 target 

### ISSUE THREAD

**Issue by papyr** [akasarto/aspnet-mvc5-starter-template#4]
Hi, I noticed a huge performance boost when I installed 4.71 for this project. In the next checkin a simple update to 4.72 .NET should be fairly fast, just right click on project->properties and after you install the below updates, you can change to 4.72 easily.

Also Bootstrap & razor Views have been updated

But now, they released runtime [4.72](https://www.microsoft.com/net/download/dotnet-framework-runtime) & updated BCL 4.72 [here ](https://support.microsoft.com/en-us/help/4054530/microsoft-net-framework-4-7-2-offline-installer-for-windows)

- [ ] Updating this and the SDK as project properties.
- [ ] Nuget updates

**Comment by akasarto** [comment]
Hey, thanks for the heads up! Upgrading to the latest .net framework version is one of the things included in the major update mentioned here: #1 .

**Comment by akasarto** [comment]
Projects are now targeting the latest .NET Framework version shipped with Visual Studio. Currently 4.7.1.
